name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          PROJECT_PATH: src/Api/PublicApi.csproj
          SOLUTION_PATH: TransactionsSummaryApi.sln
        shell: powershell
        run: |
          
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"cesarmoralesonya_TransactionsSummaryAPI" /o:"moralescorp" /d:sonar.cs.vstest.reportsPaths=".\**\*.trx" /d:sonar.cs.vscoveragexml.reportsPaths=".\**\*.coveragexml" /d:sonar.coverage.exclusions="**Test**" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build "${{env.PROJECT_PATH}}"
          dotnet test "${{env.SOLUTION_PATH}}" --collect "Code Coverage" --logger trx --results-directory "TestsResults"
          Get-ChildItem -Recurse -Filter "*.coverage" | Foreach-Object {
            $outfile = "$([System.IO.Path]::GetFileNameWithoutExtension($_.FullName)).coveragexml"
            $output = [System.IO.Path]::Combine([System.IO.Path]::GetDirectoryName($_.FullName), $outfile) 
            & $env:CodeCoveragePath\CodeCoverage.exe analyze /output:$output $_.FullName}
    
          Get-ChildItem -Recurse -Filter "*.coveragexml" | Foreach-Object { 
            $file = Join-Path -Path $_.Directory -ChildPath $_.Name
            Copy-Item $file -Destination 'TestsResults'}
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
          dotnet clean "${{env.PROJECT_PATH}}"